bucketName: card-bag-1252452307
secretId: AKIDOaaMPtjFCPZR8myZTmJ0b5OVeNtKi6IK
secretKey: SJdnvwUr6D6mHhttRP8IdnkOo14x6Smt
region: ap-chengdu
spring:
  datasource:
    url: jdbc:mysql://139.9.212.1/card_bag?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    password: zhangbaoning
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
